server:
  port: 9191

spring:
  application:
    name: spring-ai-demo
  ai:
    openai:
      api-key: sk-4ee98902af5640b5aa40bf661db88a43
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.8

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  level:
    org.springframework.ai.chat.client.advisor: debug